package def.node.zlib;
import def.js.Error;
import def.node.Buffer;
/** This class holds all the global functions and variables of the zlib package. */
public final class Globals {
    private Globals(){}
    native public static Gzip createGzip(ZlibOptions options);
    native public static Gunzip createGunzip(ZlibOptions options);
    native public static Deflate createDeflate(ZlibOptions options);
    native public static Inflate createInflate(ZlibOptions options);
    native public static DeflateRaw createDeflateRaw(ZlibOptions options);
    native public static InflateRaw createInflateRaw(ZlibOptions options);
    native public static Unzip createUnzip(ZlibOptions options);
    native public static void deflate(Buffer buf, java.util.function.BiConsumer<Error,Buffer> callback);
    native public static Buffer deflateSync(Buffer buf, ZlibOptions options);
    native public static void deflateRaw(Buffer buf, java.util.function.BiConsumer<Error,Buffer> callback);
    native public static Buffer deflateRawSync(Buffer buf, ZlibOptions options);
    native public static void gzip(Buffer buf, java.util.function.BiConsumer<Error,Buffer> callback);
    native public static Buffer gzipSync(Buffer buf, ZlibOptions options);
    native public static void gunzip(Buffer buf, java.util.function.BiConsumer<Error,Buffer> callback);
    native public static Buffer gunzipSync(Buffer buf, ZlibOptions options);
    native public static void inflate(Buffer buf, java.util.function.BiConsumer<Error,Buffer> callback);
    native public static Buffer inflateSync(Buffer buf, ZlibOptions options);
    native public static void inflateRaw(Buffer buf, java.util.function.BiConsumer<Error,Buffer> callback);
    native public static Buffer inflateRawSync(Buffer buf, ZlibOptions options);
    native public static void unzip(Buffer buf, java.util.function.BiConsumer<Error,Buffer> callback);
    native public static Buffer unzipSync(Buffer buf, ZlibOptions options);
    public static double Z_NO_FLUSH;
    public static double Z_PARTIAL_FLUSH;
    public static double Z_SYNC_FLUSH;
    public static double Z_FULL_FLUSH;
    public static double Z_FINISH;
    public static double Z_BLOCK;
    public static double Z_TREES;
    public static double Z_OK;
    public static double Z_STREAM_END;
    public static double Z_NEED_DICT;
    public static double Z_ERRNO;
    public static double Z_STREAM_ERROR;
    public static double Z_DATA_ERROR;
    public static double Z_MEM_ERROR;
    public static double Z_BUF_ERROR;
    public static double Z_VERSION_ERROR;
    public static double Z_NO_COMPRESSION;
    public static double Z_BEST_SPEED;
    public static double Z_BEST_COMPRESSION;
    public static double Z_DEFAULT_COMPRESSION;
    public static double Z_FILTERED;
    public static double Z_HUFFMAN_ONLY;
    public static double Z_RLE;
    public static double Z_FIXED;
    public static double Z_DEFAULT_STRATEGY;
    public static double Z_BINARY;
    public static double Z_TEXT;
    public static double Z_ASCII;
    public static double Z_UNKNOWN;
    public static double Z_DEFLATED;
    native public static Gzip createGzip();
    native public static Gunzip createGunzip();
    native public static Deflate createDeflate();
    native public static Inflate createInflate();
    native public static DeflateRaw createDeflateRaw();
    native public static InflateRaw createInflateRaw();
    native public static Unzip createUnzip();
    native public static Buffer deflateSync(Buffer buf);
    native public static Buffer deflateRawSync(Buffer buf);
    native public static Buffer gzipSync(Buffer buf);
    native public static Buffer gunzipSync(Buffer buf);
    native public static Buffer inflateSync(Buffer buf);
    native public static Buffer inflateRawSync(Buffer buf);
    native public static Buffer unzipSync(Buffer buf);
    native public static void deflate(String buf, java.util.function.BiConsumer<Error,Buffer> callback);
    native public static Buffer deflateSync(String buf, ZlibOptions options);
    native public static void deflateRaw(String buf, java.util.function.BiConsumer<Error,Buffer> callback);
    native public static Buffer deflateRawSync(String buf, ZlibOptions options);
    native public static Buffer deflateSync(String buf);
    native public static Buffer deflateRawSync(String buf);
}

