package def.node.path;
/**
     * A parsed path object generated by path.parse() or consumed by path.format().
     */
@jsweet.lang.Interface
public abstract class ParsedPath extends def.js.Object {
    /**
         * The root of the path such as '/' or 'c:\'
         */
    public String root;
    /**
         * The full directory path such as '/home/user/dir' or 'c:\path\dir'
         */
    public String dir;
    /**
         * The file name including extension (if any) such as 'index.html'
         */
    public String base;
    /**
         * The file extension (if any) such as '.html'
         */
    public String ext;
    /**
         * The file name without extension (if any) such as 'index'
         */
    public String name;
}

